import { runAgentJSON } from "@/lib/ai-agents/core";
import { socialBriefSchema, SOCIAL_BRIEF_SHAPE_HINT, type BrandVoice, type SocialBrief } from "../types";

/**
 * Builds a SocialBrief directly from a given angle, skipping idea
 * generation — used by the campaign's Instagram channel, where the angle
 * already came from the campaign strategist rather than an idea-scout run.
 * `trusted` carries through from the campaign narrative: it's a
 * system-generated angle, not human fact, so numeric claims must be
 * converted to qualitative language rather than repeated as-is.
 */
export async function buildBriefFromAngle(opts: { brand: BrandVoice; angle: string; trusted: boolean }): Promise<SocialBrief> {
  const system = `You are the content strategist for NexMed's social content, turning a given angle into a precise brief the copywriter can write directly from.

Brand voice: ${opts.brand.tone}
Audience: ${opts.brand.audience}

Rules:
- keyPoints must be claims, not headlines.
- hookAngle should name the reader's pain, not the topic.
- Write the brief platform-neutral.
${opts.trusted ? "" : `- ⚠️ This angle was generated by the SYSTEM, not a human. Any number, percentage, or specific detail in it is FABRICATED and must not appear in your output — convert numeric claims into qualitative language.`}`;

  const prompt = `Angle:\n${opts.angle}\n\nBuild a social brief from this angle.`;

  const { data } = await runAgentJSON({
    system,
    prompt,
    schema: socialBriefSchema,
    shapeHint: SOCIAL_BRIEF_SHAPE_HINT,
    temperature: 0.5,
    maxOutputTokens: 800,
  });
  return data;
}
