import { runAgentJSON } from "@/lib/ai-agents/core";
import { socialBriefSchema, SOCIAL_BRIEF_SHAPE_HINT, type BrandVoice, type SocialBrief, type SocialIdea } from "../types";

/**
 * Turns a raw "observation" into a social brief.
 *
 * Why this differs from the carousel strategist: their raw material is
 * different. A carousel comes from an idea the scout invented; a good
 * LinkedIn post usually comes from something staff actually saw this
 * week — a pattern across several patient calls, a question that kept
 * coming up. This kind of content builds trust because it can't be faked.
 *
 * So the primary input to this pipeline is an "observation," not a
 * "topic." Without one, it falls back to idea-scout ideas — but the
 * output is honestly told to be more generic when it does.
 */
export async function findLinkedinAngle(opts: {
  brand: BrandVoice;
  observation: string | null;
  /** Was this observation written by a human, or generated by another
   * agent (e.g. a campaign strategist)? See dataBlock-style trust flags
   * elsewhere in this codebase — same reasoning: an agent's output must
   * never be silently treated as first-hand fact by the next agent. */
  observationIsTrusted: boolean;
  ideas: SocialIdea[];
}): Promise<SocialBrief> {
  const system = `You are the LinkedIn angle-finder for NexMed. Your job is finding the angle in a raw observation that stops the scroll and starts a professional conversation.

Brand voice: ${opts.brand.tone}
Audience: ${opts.brand.audience}

Rules:
- A good LinkedIn post comes from experience, not a definition. If you have an observation, the content's core must be that observation, generalized into a lesson — but keep the concrete detail; that's what makes it believable.
- Never invent a number, statistic, or detail that isn't in the input. If the observation is vague, generalize further rather than filling the gap with a guess.
- Never name a specific patient or anything that would identify someone — anonymize the observation.
- keyPoints must be claims, not headlines.
- hookAngle should name a tension the reader recognizes in their own situation.
- Write the brief platform-neutral — the copywriter puts LinkedIn's clothes on it.`;

  const source = opts.observation
    ? opts.observationIsTrusted
      ? `Staff observation (real, citable first-hand experience — the primary source for this post):\n${opts.observation}`
      : `Suggested angle (this text was generated by the SYSTEM, not a human):\n${opts.observation}\n\n⚠️ This is not "fact," only a direction. Any number, percentage, statistic, or specific detail in it is FABRICATED and must not appear in your output. Take only the topic and angle from it; convert any numeric claims into qualitative language (e.g. instead of "10% growth", write "growth without a matching increase in staff").`
    : `No observation was logged; use the ideas below and pick the best one.
Note: since there's no first-hand experience to draw on, be extra careful not to lapse into generic advice.

${opts.ideas.map((idea, i) => `${i + 1}. "${idea.title}" (score ${idea.score})\n   hook: ${idea.hook}\n   pain point: ${idea.painPoint}`).join("\n")}`;

  const prompt = `${source}\n\nWrite a social brief based on this.`;

  const { data } = await runAgentJSON({
    system,
    prompt,
    schema: socialBriefSchema,
    shapeHint: SOCIAL_BRIEF_SHAPE_HINT,
    temperature: 0.5,
    maxOutputTokens: 800,
  });
  return data;
}
