import { runAgentJSON } from "@/lib/ai-agents/core";
import { ctaListBlock } from "../reels-cta";
import { reelsScriptSchema, REELS_SHAPE_HINT, type BrandVoice, type ReelsScript, type SocialReview } from "../types";
import type { SocialCheck } from "../social-checks";
import type { ReelsSource } from "../reels-source";

/**
 * From a link or text, produces a script meant to be read straight into a
 * camera. The key requirement: the output must be SPEAKABLE, not
 * well-written. A nicely written sentence sounds artificial read aloud —
 * so sentence structure here is short and breathable on purpose.
 */
function systemPrompt(brand: BrandVoice, hasLeadMagnet: boolean, leadMagnet: string | null): string {
  return `You are the reels copywriter for NexMed. You write scripts meant to be read straight into a camera and recorded.

Brand voice: ${brand.tone}
Never use these words or phrases: ${brand.bannedWords.join(", ") || "(none configured)"}

— Rule one: everything you write must be SPEAKABLE, not written —
Read it aloud in your head; if a sentence doesn't sit right in your mouth, break it apart. Short, breathable sentences. Stiff, written-register phrasing ("furthermore", "it is important to note") sounds fake spoken aloud — don't use it.

— Structure —
1) Hook (3-5 seconds): one sentence that stops the scroll. A sharp question, a bold claim, or naming a common mistake. No greeting, no preamble — go straight to the point. Max ~20 words.
2) Body: has a narrative arc — problem/question → simple explanation → "so what" (a takeaway useful to the viewer). Either cut jargon or explain it with an everyday example.
3) Call to action: pick EXACTLY ONE from the list below.

— Length —
About 140 words per minute of narration. Hard cap 400 words (under 3 minutes). Sweet spot 140-220 words (about a minute to a minute and a half) unless the content is genuinely dense.

— Allowed calls to action (pick exactly one) —
${ctaListBlock(hasLeadMagnet)}

Pick whichever fits this video's actual point. Say it naturally — it doesn't need to match the example word for word. Put that option's id in ctaId.${leadMagnet ? `\n\nFree resource available for this video: "${leadMagnet}"` : ""}

— Forbidden —
- No stage directions, delivery notes, or bracketed notation in the script text. Only write what's actually SAID.
- Never invent a number or statistic. If it's not in the source, state the trend or principle instead of a precise figure.
- Hashtags only in the hashtags field, never inside the caption text.
- No guaranteed-results promises or hyped ad-like tone.`;
}

function sourceBlock(source: ReelsSource): string {
  if (source.trusted) {
    return `— Raw material (${source.origin}) —\n${source.text}`;
  }
  return `— Suggested angle (this text was generated by the SYSTEM, not a human) —\n${source.text}\n\n⚠️ This is not "fact," only a direction. Any number, percentage, statistic, or specific example in it is FABRICATED and must not appear in your script. Take only the topic and angle; convert numeric claims into qualitative language.`;
}

export async function writeReelsScript(opts: { brand: BrandVoice; source: ReelsSource; leadMagnet: string | null }): Promise<ReelsScript> {
  const prompt = `${sourceBlock(opts.source)}

Read this fully, find the one point that's actually worth a video, and write a reels script based on it.`;

  const { data } = await runAgentJSON({
    system: systemPrompt(opts.brand, Boolean(opts.leadMagnet), opts.leadMagnet),
    prompt,
    schema: reelsScriptSchema,
    shapeHint: REELS_SHAPE_HINT,
    temperature: 0.7,
    maxOutputTokens: 2000,
  });
  return data;
}

export async function reviseReelsScript(opts: {
  brand: BrandVoice;
  source: ReelsSource;
  leadMagnet: string | null;
  draft: ReelsScript;
  review: SocialReview;
  failedChecks: SocialCheck[];
}): Promise<ReelsScript> {
  const prompt = `${sourceBlock(opts.source)}

— Current draft —
${JSON.stringify(opts.draft, null, 2)}

— Editor's issues (score ${opts.review.score}/100) —
${opts.review.issues.map((i) => `- ${i}`).join("\n") || "- (none)"}

— Failed deterministic checks —
${opts.failedChecks.map((c) => `- ${c.name}: ${c.note}`).join("\n") || "- (all passed)"}

Fix the script. Only change what's actually wrong; leave the rest untouched.`;

  const { data } = await runAgentJSON({
    system: systemPrompt(opts.brand, Boolean(opts.leadMagnet), opts.leadMagnet),
    prompt,
    schema: reelsScriptSchema,
    shapeHint: REELS_SHAPE_HINT,
    temperature: 0.5,
    maxOutputTokens: 2000,
  });
  return data;
}
