export type Medication = {
  name: string;
  aliases: string[];
  category: string;
  uses: string;
  typicalDosage: string;
  sideEffects: string;
  warnings: string;
};

// Curated, general-education reference for common OTC and widely-known
// prescription medications — not a substitute for the patient information
// leaflet or pharmacist advice (same disclaimer as the rest of this page).
export const medications: Medication[] = [
  {
    name: "Acetaminophen",
    aliases: ["Tylenol", "Paracetamol"],
    category: "Pain & fever relief",
    uses: "Relieves mild to moderate pain and reduces fever.",
    typicalDosage: "Adults: 325–650mg every 4–6 hours as needed. Do not exceed 3,000–4,000mg per day.",
    sideEffects: "Generally well tolerated. Rare: nausea, rash.",
    warnings: "Exceeding the daily limit can cause serious liver damage. Avoid alcohol. Check other products for hidden acetaminophen to avoid doubling up.",
  },
  {
    name: "Ibuprofen",
    aliases: ["Advil", "Motrin"],
    category: "Pain & fever relief",
    uses: "Relieves pain, inflammation, and fever (an NSAID).",
    typicalDosage: "Adults: 200–400mg every 4–6 hours as needed. Do not exceed 1,200mg/day without medical advice.",
    sideEffects: "Stomach upset, heartburn, dizziness.",
    warnings: "Take with food. Avoid if you have stomach ulcers, kidney issues, or take blood thinners — ask a pharmacist first.",
  },
  {
    name: "Aspirin",
    aliases: [],
    category: "Pain & fever relief",
    uses: "Relieves pain and fever; low-dose used for heart-attack/stroke prevention under medical guidance.",
    typicalDosage: "Pain/fever: 325–650mg every 4 hours. Heart protection: low-dose (81mg) as directed by a doctor.",
    sideEffects: "Stomach upset, increased bleeding risk.",
    warnings: "Not recommended for children/teens with viral illness (risk of Reye's syndrome). Avoid with certain blood thinners without medical advice.",
  },
  {
    name: "Cetirizine",
    aliases: ["Zyrtec"],
    category: "Allergy relief",
    uses: "Relieves sneezing, itching, runny nose, and hives from allergies.",
    typicalDosage: "Adults: 10mg once daily.",
    sideEffects: "Mild drowsiness, dry mouth.",
    warnings: "Less sedating than older antihistamines, but check before driving until you know how it affects you.",
  },
  {
    name: "Loratadine",
    aliases: ["Claritin"],
    category: "Allergy relief",
    uses: "Non-drowsy relief for allergy symptoms like sneezing and itchy eyes.",
    typicalDosage: "Adults: 10mg once daily.",
    sideEffects: "Headache, rarely drowsiness.",
    warnings: "Generally non-sedating, but individual response varies.",
  },
  {
    name: "Diphenhydramine",
    aliases: ["Benadryl"],
    category: "Allergy relief",
    uses: "Relieves allergy symptoms and is also used as a short-term sleep aid.",
    typicalDosage: "Adults: 25–50mg every 4–6 hours as needed.",
    sideEffects: "Significant drowsiness, dry mouth, blurred vision.",
    warnings: "Do not drive or operate machinery. Avoid with alcohol. Use caution in older adults (higher fall/confusion risk).",
  },
  {
    name: "Pseudoephedrine",
    aliases: ["Sudafed"],
    category: "Cold & flu",
    uses: "Relieves nasal and sinus congestion.",
    typicalDosage: "Adults: 60mg every 4–6 hours, max 240mg/day.",
    sideEffects: "Increased heart rate, jitteriness, trouble sleeping.",
    warnings: "Avoid if you have high blood pressure or heart conditions without medical advice. Kept behind the pharmacy counter in many regions.",
  },
  {
    name: "Dextromethorphan",
    aliases: ["Robitussin DM", "Delsym"],
    category: "Cold & flu",
    uses: "Suppresses dry, non-productive cough.",
    typicalDosage: "Adults: follow product label, typically every 6–12 hours depending on formulation.",
    sideEffects: "Drowsiness, dizziness, nausea.",
    warnings: "Do not combine with MAOI antidepressants. Check combination cold products to avoid duplicate ingredients.",
  },
  {
    name: "Metformin",
    aliases: ["Glucophage"],
    category: "Diabetes care",
    uses: "First-line prescription medication to manage blood sugar in type 2 diabetes.",
    typicalDosage: "As prescribed — commonly started at 500mg once or twice daily with meals, adjusted by a doctor.",
    sideEffects: "GI upset (nausea, diarrhea), especially when starting — usually improves over time.",
    warnings: "Requires a prescription. Take with food. Tell your doctor before any imaging scan requiring contrast dye.",
  },
  {
    name: "Semaglutide",
    aliases: ["Ozempic", "Wegovy"],
    category: "Diabetes care",
    uses: "Prescription injectable for type 2 diabetes management and, at higher doses, weight management.",
    typicalDosage: "Weekly injection, dose titrated by a prescriber (commonly starting at 0.25mg/week).",
    sideEffects: "Nausea, vomiting, diarrhea, especially during dose increases.",
    warnings: "Prescription only. Requires prior authorization with most insurers. Not for use in certain thyroid cancer histories — discuss with your doctor.",
  },
  {
    name: "Lisinopril",
    aliases: ["Prinivil", "Zestril"],
    category: "Heart health",
    uses: "Prescription ACE inhibitor for high blood pressure and heart failure.",
    typicalDosage: "As prescribed — commonly 10–40mg once daily.",
    sideEffects: "Dry cough, dizziness, elevated potassium.",
    warnings: "Prescription only. Avoid in pregnancy. Regular blood pressure and kidney function monitoring recommended.",
  },
  {
    name: "Atorvastatin",
    aliases: ["Lipitor"],
    category: "Heart health",
    uses: "Prescription statin to lower LDL cholesterol and reduce cardiovascular risk.",
    typicalDosage: "As prescribed — commonly 10–80mg once daily, usually in the evening.",
    sideEffects: "Muscle aches, mild liver enzyme changes.",
    warnings: "Prescription only. Report unexplained muscle pain to your doctor. Avoid grapefruit juice in large amounts.",
  },
  {
    name: "Omeprazole",
    aliases: ["Prilosec"],
    category: "Digestive health",
    uses: "Reduces stomach acid to relieve frequent heartburn/acid reflux.",
    typicalDosage: "Adults (OTC use): 20mg once daily for up to 14 days.",
    sideEffects: "Headache, stomach pain, nausea.",
    warnings: "OTC course shouldn't exceed 14 days more than 3x/year without a doctor's advice. Can affect absorption of some other medications.",
  },
  {
    name: "Famotidine",
    aliases: ["Pepcid"],
    category: "Digestive health",
    uses: "Reduces stomach acid to relieve and prevent heartburn.",
    typicalDosage: "Adults (OTC use): 10–20mg, up to twice daily.",
    sideEffects: "Headache, dizziness, constipation.",
    warnings: "See a doctor if heartburn persists more than 2 weeks or worsens.",
  },
  {
    name: "Loperamide",
    aliases: ["Imodium"],
    category: "Digestive health",
    uses: "Controls symptoms of diarrhea.",
    typicalDosage: "Adults: 4mg initially, then 2mg after each loose stool, max 8mg/day (OTC use).",
    sideEffects: "Constipation, dizziness, drowsiness.",
    warnings: "Do not use if you have bloody or black stool or a fever — see a doctor. Not for suspected bacterial infections without medical advice.",
  },
  {
    name: "Amoxicillin",
    aliases: [],
    category: "Antibiotics",
    uses: "Prescription antibiotic for bacterial infections (ear, throat, chest, urinary, and others).",
    typicalDosage: "As prescribed — commonly 250–500mg two to three times daily, depending on the infection.",
    sideEffects: "Nausea, diarrhea, rash.",
    warnings: "Prescription only. Finish the full course even if you feel better. Tell your pharmacist about any penicillin allergy.",
  },
  {
    name: "Azithromycin",
    aliases: ["Zithromax", "Z-Pak"],
    category: "Antibiotics",
    uses: "Prescription antibiotic for respiratory, skin, and certain other bacterial infections.",
    typicalDosage: "As prescribed — commonly a short course such as 500mg on day 1, then 250mg daily for 4 more days.",
    sideEffects: "Nausea, stomach pain, diarrhea.",
    warnings: "Prescription only. Can interact with several other medications — always share your full medication list with the prescriber.",
  },
  {
    name: "Sertraline",
    aliases: ["Zoloft"],
    category: "Mental health",
    uses: "Prescription SSRI for depression, anxiety, and related conditions.",
    typicalDosage: "As prescribed — commonly started at 25–50mg once daily, adjusted gradually.",
    sideEffects: "Nausea, sleep changes, sexual side effects, especially when starting.",
    warnings: "Prescription only. Do not stop suddenly — taper under medical guidance. Full effect can take several weeks.",
  },
  {
    name: "Alprazolam",
    aliases: ["Xanax"],
    category: "Mental health",
    uses: "Prescription benzodiazepine for short-term treatment of anxiety.",
    typicalDosage: "As prescribed — lowest effective dose for the shortest time needed.",
    sideEffects: "Drowsiness, dizziness, memory or coordination issues.",
    warnings: "Prescription only, controlled substance. Risk of dependence with prolonged use. Never combine with alcohol or opioids. Do not stop abruptly.",
  },
  {
    name: "Albuterol",
    aliases: ["Ventolin", "ProAir"],
    category: "Respiratory",
    uses: "Prescription fast-acting inhaler that relieves asthma and COPD symptoms like wheezing and shortness of breath.",
    typicalDosage: "As prescribed — commonly 1–2 puffs every 4–6 hours as needed for symptoms.",
    sideEffects: "Jitteriness, fast heartbeat, mild tremor.",
    warnings: "Prescription only. If you're using it more than twice a week for symptom relief, talk to your doctor about your asthma control plan.",
  },
  {
    name: "Fluticasone",
    aliases: ["Flonase"],
    category: "Allergy relief",
    uses: "Nasal spray that relieves nasal allergy symptoms — congestion, sneezing, runny/itchy nose.",
    typicalDosage: "Adults (OTC use): 1–2 sprays per nostril once daily.",
    sideEffects: "Nasal dryness or irritation, occasional nosebleed.",
    warnings: "Takes a few days of regular use for full effect. See a doctor if symptoms don't improve after a week of daily use.",
  },
  {
    name: "Levothyroxine",
    aliases: ["Synthroid"],
    category: "Thyroid health",
    uses: "Prescription hormone replacement for an underactive thyroid (hypothyroidism).",
    typicalDosage: "As prescribed — highly individualized, typically taken once daily on an empty stomach.",
    sideEffects: "Usually minimal at the correct dose; too high a dose can cause rapid heartbeat, anxiety, or weight loss.",
    warnings: "Prescription only. Take at the same time each day, on an empty stomach, and separate from calcium/iron supplements by several hours.",
  },
  {
    name: "Melatonin",
    aliases: [],
    category: "Sleep",
    uses: "Over-the-counter supplement used to help with occasional sleeplessness or jet lag.",
    typicalDosage: "Adults: commonly 1–5mg, taken 30–60 minutes before bedtime.",
    sideEffects: "Next-day grogginess, headache, mild nausea.",
    warnings: "Not tightly regulated as a supplement — dosages can vary by brand. Talk to a pharmacist before use if pregnant, breastfeeding, or on other medications.",
  },
  {
    name: "Hydrocortisone cream",
    aliases: ["Cortizone-10"],
    category: "Skincare",
    uses: "Relieves itching, redness, and irritation from insect bites, rashes, and mild eczema.",
    typicalDosage: "Apply a thin layer to the affected area up to 4 times daily (OTC strength), for no more than 7 days unless advised otherwise.",
    sideEffects: "Mild skin thinning or irritation with prolonged use.",
    warnings: "Avoid use on broken skin, the face, or in the eyes unless directed by a doctor. See a doctor if the condition doesn't improve.",
  },
  {
    name: "Warfarin",
    aliases: ["Coumadin"],
    category: "Heart health",
    uses: "Prescription blood thinner to prevent and treat blood clots.",
    typicalDosage: "As prescribed — highly individualized and requires regular blood testing (INR) to adjust the dose.",
    sideEffects: "Increased bruising or bleeding risk.",
    warnings: "Prescription only. Many food (especially vitamin K-rich greens) and drug interactions — consistency matters. Never adjust the dose yourself.",
  },
  {
    name: "Multivitamin",
    aliases: [],
    category: "Vitamins & supplements",
    uses: "General nutritional support to help fill gaps in a typical diet.",
    typicalDosage: "As directed on the product label, typically once daily with food.",
    sideEffects: "Mild stomach upset if taken without food.",
    warnings: "Not a substitute for a balanced diet. Keep iron-containing formulas away from children — iron overdose in kids is dangerous.",
  },
  {
    name: "Vitamin D3",
    aliases: ["Cholecalciferol"],
    category: "Vitamins & supplements",
    uses: "Supports bone health and immune function, especially with low sun exposure.",
    typicalDosage: "Commonly 600–2,000 IU daily for adults, though needs vary — a pharmacist or doctor can advise based on blood levels.",
    sideEffects: "Rare at recommended doses; very high doses over time can raise blood calcium.",
    warnings: "Don't exceed the label dose without medical guidance, especially if also taking calcium supplements.",
  },

  // --- Respiratory / inhalers ---
  {
    name: "Fluticasone/Salmeterol",
    aliases: ["Advair"],
    category: "Respiratory",
    uses: "Prescription combination inhaler (steroid + long-acting bronchodilator) for daily asthma/COPD control — not for sudden symptoms.",
    typicalDosage: "As prescribed — typically 1 inhalation twice daily, roughly 12 hours apart.",
    sideEffects: "Throat irritation, oral thrush (rinse mouth after use), headache.",
    warnings: "Prescription only. This is a daily controller, not a rescue inhaler — keep a fast-acting inhaler (like albuterol) on hand for sudden symptoms.",
  },
  {
    name: "Budesonide",
    aliases: ["Pulmicort"],
    category: "Respiratory",
    uses: "Prescription inhaled steroid for daily asthma control (also used as a nasal spray for allergies).",
    typicalDosage: "As prescribed — commonly 1–2 inhalations once or twice daily.",
    sideEffects: "Throat irritation, hoarseness, oral thrush.",
    warnings: "Prescription only (inhaler form). Rinse mouth after each use. Not a rescue inhaler for sudden breathing trouble.",
  },
  {
    name: "Ipratropium",
    aliases: ["Atrovent"],
    category: "Respiratory",
    uses: "Prescription inhaler that relaxes airways, used for COPD and sometimes asthma.",
    typicalDosage: "As prescribed — commonly 2 inhalations up to 4 times daily.",
    sideEffects: "Dry mouth, cough, headache.",
    warnings: "Prescription only. Avoid spraying near eyes — can cause blurred vision or eye discomfort.",
  },
  {
    name: "Montelukast",
    aliases: ["Singulair"],
    category: "Respiratory",
    uses: "Prescription daily tablet for asthma control and seasonal allergy symptoms.",
    typicalDosage: "As prescribed — commonly 10mg once daily in the evening for adults.",
    sideEffects: "Headache, stomach upset.",
    warnings: "Prescription only. Rare reports of mood or behavior changes — tell your doctor about any new anxiety, sleep problems, or agitation.",
  },

  // --- Cholesterol (additional) ---
  {
    name: "Rosuvastatin",
    aliases: ["Crestor"],
    category: "Cholesterol",
    uses: "Prescription statin to lower LDL cholesterol and reduce cardiovascular risk.",
    typicalDosage: "As prescribed — commonly 5–40mg once daily.",
    sideEffects: "Muscle aches, headache, mild liver enzyme changes.",
    warnings: "Prescription only. Report unexplained muscle pain or weakness to your doctor promptly.",
  },
  {
    name: "Simvastatin",
    aliases: ["Zocor"],
    category: "Cholesterol",
    uses: "Prescription statin to lower LDL cholesterol.",
    typicalDosage: "As prescribed — commonly 10–40mg once daily, taken in the evening.",
    sideEffects: "Muscle aches, digestive upset.",
    warnings: "Prescription only. Avoid grapefruit juice. Has more drug interactions than some other statins — share your full medication list with your pharmacist.",
  },
  {
    name: "Ezetimibe",
    aliases: ["Zetia"],
    category: "Cholesterol",
    uses: "Prescription medication that lowers cholesterol absorption from food, often combined with a statin.",
    typicalDosage: "As prescribed — commonly 10mg once daily.",
    sideEffects: "Diarrhea, muscle aches, fatigue.",
    warnings: "Prescription only. Works differently than statins and is sometimes used together with one for added effect.",
  },

  // --- Mental health (additional) ---
  {
    name: "Fluoxetine",
    aliases: ["Prozac"],
    category: "Mental health",
    uses: "Prescription SSRI for depression, anxiety, OCD, and other conditions.",
    typicalDosage: "As prescribed — commonly started at 10–20mg once daily.",
    sideEffects: "Nausea, insomnia, restlessness, especially when starting.",
    warnings: "Prescription only. Do not stop suddenly. Can take several weeks for full effect. Tell your doctor about all other medications due to interaction risk.",
  },
  {
    name: "Escitalopram",
    aliases: ["Lexapro"],
    category: "Mental health",
    uses: "Prescription SSRI for depression and generalized anxiety disorder.",
    typicalDosage: "As prescribed — commonly 10mg once daily, sometimes increased to 20mg.",
    sideEffects: "Nausea, sleep changes, sexual side effects.",
    warnings: "Prescription only. Do not stop abruptly — taper under medical guidance.",
  },
  {
    name: "Bupropion",
    aliases: ["Wellbutrin"],
    category: "Mental health",
    uses: "Prescription antidepressant, also used to support smoking cessation.",
    typicalDosage: "As prescribed — varies by formulation (immediate, SR, or XL release).",
    sideEffects: "Dry mouth, insomnia, headache, decreased appetite.",
    warnings: "Prescription only. Carries a seizure-risk warning at higher doses — tell your doctor about any history of seizures or eating disorders.",
  },
  {
    name: "Trazodone",
    aliases: ["Desyrel"],
    category: "Mental health",
    uses: "Prescription antidepressant, commonly used off-label at low doses to help with sleep.",
    typicalDosage: "As prescribed — sleep-support doses are typically much lower than antidepressant doses.",
    sideEffects: "Drowsiness, dizziness, dry mouth.",
    warnings: "Prescription only. Can cause next-morning grogginess. Rare but serious risk of prolonged erection (priapism) in men — seek care immediately if this occurs.",
  },

  // --- HIV / antiviral ---
  {
    name: "Emtricitabine/Tenofovir",
    aliases: ["Truvada"],
    category: "HIV & antiviral",
    uses: "Prescription combination used both to treat HIV (as part of a regimen) and for PrEP (pre-exposure prophylaxis) to help prevent HIV in people at risk.",
    typicalDosage: "As prescribed — typically one tablet once daily.",
    sideEffects: "Nausea, headache, mild kidney or bone density changes with long-term use.",
    warnings: "Prescription only. For PrEP, consistent daily use is key to effectiveness and requires regular follow-up testing. Not a substitute for other prevention methods.",
  },
  {
    name: "Dolutegravir",
    aliases: ["Tivicay"],
    category: "HIV & antiviral",
    uses: "Prescription antiretroviral (integrase inhibitor) used as part of combination therapy to treat HIV.",
    typicalDosage: "As prescribed — commonly once daily as part of a multi-drug regimen.",
    sideEffects: "Headache, insomnia, mild weight gain.",
    warnings: "Prescription only. Must be taken as part of a full regimen exactly as prescribed — missed doses can allow resistance to develop. Many drug interactions; disclose all medications to your provider.",
  },
  {
    name: "Efavirenz",
    aliases: ["Sustiva"],
    category: "HIV & antiviral",
    uses: "Prescription antiretroviral used as part of combination therapy to treat HIV.",
    typicalDosage: "As prescribed — commonly once daily at bedtime as part of a multi-drug regimen.",
    sideEffects: "Vivid dreams, dizziness, drowsiness, especially in the first weeks.",
    warnings: "Prescription only. Taking at bedtime on an empty stomach can reduce dizziness. Significant interactions with many other drugs — always check with your pharmacist.",
  },
  {
    name: "Oseltamivir",
    aliases: ["Tamiflu"],
    category: "HIV & antiviral",
    uses: "Prescription antiviral for treating or preventing influenza (flu).",
    typicalDosage: "As prescribed — commonly 75mg twice daily for 5 days when started early in illness.",
    sideEffects: "Nausea, vomiting, headache.",
    warnings: "Prescription only. Most effective when started within 48 hours of symptom onset. Take with food to reduce nausea.",
  },

  // --- Blood pressure (additional) ---
  {
    name: "Amlodipine",
    aliases: ["Norvasc"],
    category: "Heart health",
    uses: "Prescription calcium channel blocker for high blood pressure and chest pain (angina).",
    typicalDosage: "As prescribed — commonly 2.5–10mg once daily.",
    sideEffects: "Swelling in the ankles/feet, flushing, dizziness.",
    warnings: "Prescription only. Rise slowly from sitting/lying to avoid dizziness.",
  },
  {
    name: "Losartan",
    aliases: ["Cozaar"],
    category: "Heart health",
    uses: "Prescription ARB (angiotensin receptor blocker) for high blood pressure and kidney protection in diabetes.",
    typicalDosage: "As prescribed — commonly 25–100mg once daily.",
    sideEffects: "Dizziness, elevated potassium.",
    warnings: "Prescription only. Avoid in pregnancy. Often used as an alternative for people who can't tolerate ACE inhibitors like lisinopril due to cough.",
  },
  {
    name: "Metoprolol",
    aliases: ["Lopressor", "Toprol-XL"],
    category: "Heart health",
    uses: "Prescription beta-blocker for high blood pressure, heart rhythm issues, and after a heart attack.",
    typicalDosage: "As prescribed — varies widely by formulation and condition being treated.",
    sideEffects: "Fatigue, dizziness, cold hands/feet, slowed heart rate.",
    warnings: "Prescription only. Do not stop abruptly — can cause a dangerous rebound in heart rate/blood pressure. Taper only under medical guidance.",
  },

  // --- Diabetes (additional) ---
  {
    name: "Insulin glargine",
    aliases: ["Lantus"],
    category: "Diabetes care",
    uses: "Prescription long-acting insulin for managing blood sugar in type 1 or type 2 diabetes.",
    typicalDosage: "As prescribed — individualized dose, typically injected once daily at the same time each day.",
    sideEffects: "Low blood sugar (hypoglycemia), injection site reactions, weight gain.",
    warnings: "Prescription only. Requires proper storage (refrigerated until opened) and rotation of injection sites. Know the signs of low blood sugar and how to treat it.",
  },
  {
    name: "Glipizide",
    aliases: ["Glucotrol"],
    category: "Diabetes care",
    uses: "Prescription oral medication that helps the pancreas release more insulin to lower blood sugar in type 2 diabetes.",
    typicalDosage: "As prescribed — commonly taken 30 minutes before a meal.",
    sideEffects: "Low blood sugar, weight gain, mild stomach upset.",
    warnings: "Prescription only. Risk of hypoglycemia if a meal is skipped after dosing — take with or shortly before food.",
  },
  {
    name: "Insulin lispro",
    aliases: ["Humalog"],
    category: "Diabetes care",
    uses: "Prescription fast-acting (rapid) insulin, typically taken at mealtimes to control blood sugar spikes from eating.",
    typicalDosage: "As prescribed — individualized, usually injected shortly before a meal.",
    sideEffects: "Low blood sugar (hypoglycemia), injection site reactions.",
    warnings: "Prescription only. Timing with meals matters — taking it without eating soon after can cause dangerously low blood sugar.",
  },
  {
    name: "Insulin NPH",
    aliases: ["Humulin N", "Novolin N"],
    category: "Diabetes care",
    uses: "Prescription intermediate-acting insulin used to provide longer background blood sugar control.",
    typicalDosage: "As prescribed — often once or twice daily, individualized to the person.",
    sideEffects: "Low blood sugar, injection site reactions, weight gain.",
    warnings: "Prescription only. Cloudy suspension — gently roll (don't shake) before use to mix evenly.",
  },

  // --- Other common categories ---
  {
    name: "Levetiracetam",
    aliases: ["Keppra"],
    category: "Neurology",
    uses: "Prescription anti-seizure medication used to treat epilepsy.",
    typicalDosage: "As prescribed — individualized, often started low and increased gradually.",
    sideEffects: "Drowsiness, irritability, mood changes.",
    warnings: "Prescription only. Do not stop suddenly — can trigger seizures. Report new mood or behavior changes to your doctor.",
  },
  {
    name: "Sumatriptan",
    aliases: ["Imitrex"],
    category: "Neurology",
    uses: "Prescription medication for treating acute migraine attacks.",
    typicalDosage: "As prescribed — commonly one dose at migraine onset, may repeat after 2 hours if needed (max doses per day apply).",
    sideEffects: "Tingling, flushing, chest tightness, drowsiness.",
    warnings: "Prescription only. Not for people with certain heart conditions or uncontrolled high blood pressure — discuss your history with your doctor.",
  },
  {
    name: "Alendronate",
    aliases: ["Fosamax"],
    category: "Bone health",
    uses: "Prescription bisphosphonate to treat and prevent osteoporosis.",
    typicalDosage: "As prescribed — commonly once weekly, taken first thing in the morning on an empty stomach.",
    sideEffects: "Heartburn, stomach upset, muscle/joint pain.",
    warnings: "Prescription only. Stay upright for at least 30 minutes after taking and before eating to reduce esophagus irritation.",
  },
  {
    name: "Allopurinol",
    aliases: ["Zyloprim"],
    category: "Other conditions",
    uses: "Prescription medication that lowers uric acid to prevent gout attacks.",
    typicalDosage: "As prescribed — commonly started low (e.g. 100mg daily) and increased gradually.",
    sideEffects: "Rash, mild stomach upset.",
    warnings: "Prescription only. Can trigger a gout flare when first started — your doctor may prescribe something for flare prevention initially. Report any rash promptly, as rare but serious reactions can occur.",
  },
  {
    name: "Ethinyl estradiol/Norethindrone",
    aliases: ["a common combined birth control pill"],
    category: "Other conditions",
    uses: "Prescription combined oral contraceptive to prevent pregnancy; also used to help regulate periods and reduce menstrual symptoms.",
    typicalDosage: "As prescribed — one tablet daily, typically at the same time each day.",
    sideEffects: "Nausea, breast tenderness, breakthrough bleeding, especially in the first few months.",
    warnings: "Prescription only. Smoking increases blood clot risk, especially over age 35 — discuss your full health history with your prescriber.",
  },

  // --- Eye drops ---
  {
    name: "Artificial tears",
    aliases: ["Refresh", "Systane"],
    category: "Eye care",
    uses: "Lubricates and relieves dry, irritated eyes.",
    typicalDosage: "1–2 drops in the affected eye(s) as needed, per product label.",
    sideEffects: "Mild, temporary blurred vision right after use.",
    warnings: "If wearing contact lenses, check whether the product is safe to use with lenses in. See a doctor if irritation persists or worsens.",
  },
  {
    name: "Ketotifen eye drops",
    aliases: ["Zaditor", "Alaway"],
    category: "Eye care",
    uses: "Relieves itchy, red eyes caused by allergies.",
    typicalDosage: "Adults and children 3+: 1 drop in each affected eye every 8–12 hours (OTC use).",
    sideEffects: "Mild stinging, headache.",
    warnings: "Remove contact lenses before use and wait at least 10 minutes before reinserting.",
  },
  {
    name: "Latanoprost",
    aliases: ["Xalatan"],
    category: "Eye care",
    uses: "Prescription eye drop that lowers eye pressure to treat glaucoma or high eye pressure.",
    typicalDosage: "As prescribed — typically 1 drop in the affected eye(s) once daily, usually in the evening.",
    sideEffects: "Eye redness, eyelash growth, gradual darkening of the iris color with long-term use.",
    warnings: "Prescription only. Consistent daily use is important to protect vision — don't skip doses. Tell your doctor about all eye conditions before starting.",
  },
  {
    name: "Ofloxacin eye drops",
    aliases: ["Ocuflox"],
    category: "Eye care",
    uses: "Prescription antibiotic eye drop for bacterial eye infections (e.g. conjunctivitis).",
    typicalDosage: "As prescribed — commonly 1–2 drops every 2–4 hours initially, then less often as the infection improves.",
    sideEffects: "Temporary stinging, blurred vision right after use.",
    warnings: "Prescription only. Finish the full course even if the eye looks better. Don't share eye drops between people or eyes if only one eye is infected.",
  },

  // --- Creams & topicals ---
  {
    name: "Clotrimazole cream",
    aliases: ["Lotrimin"],
    category: "Skincare",
    uses: "Treats fungal skin infections like athlete's foot, jock itch, and ringworm.",
    typicalDosage: "Apply a thin layer to the affected area twice daily for 2–4 weeks, per product label.",
    sideEffects: "Mild burning, redness, or irritation at the application site.",
    warnings: "Keep using for the full recommended time even if symptoms improve early, to prevent recurrence. See a doctor if there's no improvement in 2 weeks.",
  },
  {
    name: "Benzoyl peroxide",
    aliases: ["PanOxyl"],
    category: "Skincare",
    uses: "Treats acne by reducing acne-causing bacteria and excess oil.",
    typicalDosage: "Apply a thin layer to affected areas once or twice daily, starting with lower strengths.",
    sideEffects: "Dryness, peeling, mild redness, especially when starting.",
    warnings: "Can bleach clothing, towels, and hair — use white towels/pillowcases. Start with lower concentrations to reduce irritation, and always use sunscreen during the day.",
  },
  {
    name: "Mupirocin",
    aliases: ["Bactroban"],
    category: "Skincare",
    uses: "Prescription antibiotic ointment for minor bacterial skin infections (e.g. impetigo).",
    typicalDosage: "As prescribed — commonly applied 2–3 times daily for 5–10 days.",
    sideEffects: "Mild burning, itching, or redness at the application site.",
    warnings: "Prescription only. Finish the full course. Avoid contact with eyes.",
  },
  {
    name: "Tretinoin cream",
    aliases: ["Retin-A"],
    category: "Skincare",
    uses: "Prescription retinoid for acne and to reduce fine lines/sun damage.",
    typicalDosage: "As prescribed — typically a pea-sized amount applied at night, starting a few times a week and increasing as tolerated.",
    sideEffects: "Dryness, peeling, redness, increased sun sensitivity.",
    warnings: "Prescription only. Use sunscreen daily — skin becomes more sensitive to sunburn. Not recommended during pregnancy; discuss with your doctor.",
  },
  {
    name: "Permethrin cream",
    aliases: ["Elimite"],
    category: "Skincare",
    uses: "Treats scabies and head lice.",
    typicalDosage: "Applied as a single treatment per product/prescriber instructions, left on for a specified time (commonly 8–14 hours) then washed off.",
    sideEffects: "Itching, mild burning or stinging.",
    warnings: "Follow instructions precisely — household contacts and bedding/clothing may need treatment too. A repeat treatment is sometimes needed after 1–2 weeks.",
  },

  // --- Shampoos ---
  {
    name: "Ketoconazole shampoo",
    aliases: ["Nizoral"],
    category: "Hair & scalp",
    uses: "Treats dandruff and seborrheic dermatitis caused by yeast/fungus on the scalp.",
    typicalDosage: "Use every 3–4 days for up to 8 weeks (OTC strength), leaving on the scalp for 3–5 minutes before rinsing.",
    sideEffects: "Dry or oily scalp changes, mild irritation.",
    warnings: "Avoid contact with eyes. If no improvement after several weeks, see a doctor or dermatologist.",
  },
  {
    name: "Selenium sulfide shampoo",
    aliases: ["Selsun Blue"],
    category: "Hair & scalp",
    uses: "Treats dandruff and flaking, itchy scalp.",
    typicalDosage: "Use twice weekly for the first 2 weeks, then as needed to control symptoms.",
    sideEffects: "Scalp irritation, discoloration of light-colored/permed or dyed hair.",
    warnings: "Rinse thoroughly and avoid contact with eyes. Discontinue if irritation is significant.",
  },
  {
    name: "Coal tar shampoo",
    aliases: ["Neutrogena T/Gel"],
    category: "Hair & scalp",
    uses: "Relieves scalp itching and flaking from dandruff, psoriasis, or seborrheic dermatitis.",
    typicalDosage: "Use 2–3 times a week, or as directed, leaving on the scalp for a few minutes before rinsing.",
    sideEffects: "Scalp irritation, dryness, temporary discoloration of light hair.",
    warnings: "Can increase sun sensitivity of treated skin — take care with sun exposure. Avoid contact with eyes.",
  },
  {
    name: "Minoxidil",
    aliases: ["Rogaine"],
    category: "Hair & scalp",
    uses: "Topical treatment (liquid or foam) to help regrow hair in pattern hair loss.",
    typicalDosage: "Apply to the scalp once or twice daily per product strength/label; results typically take several months of consistent use.",
    sideEffects: "Scalp irritation, unwanted facial hair if it spreads beyond the scalp, temporary increased shedding when starting.",
    warnings: "Requires ongoing use to maintain results — hair loss typically resumes if stopped. Not for use on other body areas.",
  },
];
