export type Medication = {
  name: string;
  aliases: string[];
  category: string;
  uses: string;
  typicalDosage: string;
  sideEffects: string;
  warnings: string;
};

// Curated, general-education reference for common OTC and widely-known
// prescription medications — not a substitute for the patient information
// leaflet or pharmacist advice (same disclaimer as the rest of this page).
export const medications: Medication[] = [
  {
    name: "Acetaminophen",
    aliases: ["Tylenol", "Paracetamol"],
    category: "Pain & fever relief",
    uses: "Relieves mild to moderate pain and reduces fever.",
    typicalDosage: "Adults: 325–650mg every 4–6 hours as needed. Do not exceed 3,000–4,000mg per day.",
    sideEffects: "Generally well tolerated. Rare: nausea, rash.",
    warnings: "Exceeding the daily limit can cause serious liver damage. Avoid alcohol. Check other products for hidden acetaminophen to avoid doubling up.",
  },
  {
    name: "Ibuprofen",
    aliases: ["Advil", "Motrin"],
    category: "Pain & fever relief",
    uses: "Relieves pain, inflammation, and fever (an NSAID).",
    typicalDosage: "Adults: 200–400mg every 4–6 hours as needed. Do not exceed 1,200mg/day without medical advice.",
    sideEffects: "Stomach upset, heartburn, dizziness.",
    warnings: "Take with food. Avoid if you have stomach ulcers, kidney issues, or take blood thinners — ask a pharmacist first.",
  },
  {
    name: "Aspirin",
    aliases: [],
    category: "Pain & fever relief",
    uses: "Relieves pain and fever; low-dose used for heart-attack/stroke prevention under medical guidance.",
    typicalDosage: "Pain/fever: 325–650mg every 4 hours. Heart protection: low-dose (81mg) as directed by a doctor.",
    sideEffects: "Stomach upset, increased bleeding risk.",
    warnings: "Not recommended for children/teens with viral illness (risk of Reye's syndrome). Avoid with certain blood thinners without medical advice.",
  },
  {
    name: "Cetirizine",
    aliases: ["Zyrtec"],
    category: "Allergy relief",
    uses: "Relieves sneezing, itching, runny nose, and hives from allergies.",
    typicalDosage: "Adults: 10mg once daily.",
    sideEffects: "Mild drowsiness, dry mouth.",
    warnings: "Less sedating than older antihistamines, but check before driving until you know how it affects you.",
  },
  {
    name: "Loratadine",
    aliases: ["Claritin"],
    category: "Allergy relief",
    uses: "Non-drowsy relief for allergy symptoms like sneezing and itchy eyes.",
    typicalDosage: "Adults: 10mg once daily.",
    sideEffects: "Headache, rarely drowsiness.",
    warnings: "Generally non-sedating, but individual response varies.",
  },
  {
    name: "Diphenhydramine",
    aliases: ["Benadryl"],
    category: "Allergy relief",
    uses: "Relieves allergy symptoms and is also used as a short-term sleep aid.",
    typicalDosage: "Adults: 25–50mg every 4–6 hours as needed.",
    sideEffects: "Significant drowsiness, dry mouth, blurred vision.",
    warnings: "Do not drive or operate machinery. Avoid with alcohol. Use caution in older adults (higher fall/confusion risk).",
  },
  {
    name: "Pseudoephedrine",
    aliases: ["Sudafed"],
    category: "Cold & flu",
    uses: "Relieves nasal and sinus congestion.",
    typicalDosage: "Adults: 60mg every 4–6 hours, max 240mg/day.",
    sideEffects: "Increased heart rate, jitteriness, trouble sleeping.",
    warnings: "Avoid if you have high blood pressure or heart conditions without medical advice. Kept behind the pharmacy counter in many regions.",
  },
  {
    name: "Dextromethorphan",
    aliases: ["Robitussin DM", "Delsym"],
    category: "Cold & flu",
    uses: "Suppresses dry, non-productive cough.",
    typicalDosage: "Adults: follow product label, typically every 6–12 hours depending on formulation.",
    sideEffects: "Drowsiness, dizziness, nausea.",
    warnings: "Do not combine with MAOI antidepressants. Check combination cold products to avoid duplicate ingredients.",
  },
  {
    name: "Metformin",
    aliases: ["Glucophage"],
    category: "Diabetes care",
    uses: "First-line prescription medication to manage blood sugar in type 2 diabetes.",
    typicalDosage: "As prescribed — commonly started at 500mg once or twice daily with meals, adjusted by a doctor.",
    sideEffects: "GI upset (nausea, diarrhea), especially when starting — usually improves over time.",
    warnings: "Requires a prescription. Take with food. Tell your doctor before any imaging scan requiring contrast dye.",
  },
  {
    name: "Semaglutide",
    aliases: ["Ozempic", "Wegovy"],
    category: "Diabetes care",
    uses: "Prescription injectable for type 2 diabetes management and, at higher doses, weight management.",
    typicalDosage: "Weekly injection, dose titrated by a prescriber (commonly starting at 0.25mg/week).",
    sideEffects: "Nausea, vomiting, diarrhea, especially during dose increases.",
    warnings: "Prescription only. Requires prior authorization with most insurers. Not for use in certain thyroid cancer histories — discuss with your doctor.",
  },
  {
    name: "Lisinopril",
    aliases: ["Prinivil", "Zestril"],
    category: "Heart health",
    uses: "Prescription ACE inhibitor for high blood pressure and heart failure.",
    typicalDosage: "As prescribed — commonly 10–40mg once daily.",
    sideEffects: "Dry cough, dizziness, elevated potassium.",
    warnings: "Prescription only. Avoid in pregnancy. Regular blood pressure and kidney function monitoring recommended.",
  },
  {
    name: "Atorvastatin",
    aliases: ["Lipitor"],
    category: "Heart health",
    uses: "Prescription statin to lower LDL cholesterol and reduce cardiovascular risk.",
    typicalDosage: "As prescribed — commonly 10–80mg once daily, usually in the evening.",
    sideEffects: "Muscle aches, mild liver enzyme changes.",
    warnings: "Prescription only. Report unexplained muscle pain to your doctor. Avoid grapefruit juice in large amounts.",
  },
  {
    name: "Omeprazole",
    aliases: ["Prilosec"],
    category: "Digestive health",
    uses: "Reduces stomach acid to relieve frequent heartburn/acid reflux.",
    typicalDosage: "Adults (OTC use): 20mg once daily for up to 14 days.",
    sideEffects: "Headache, stomach pain, nausea.",
    warnings: "OTC course shouldn't exceed 14 days more than 3x/year without a doctor's advice. Can affect absorption of some other medications.",
  },
  {
    name: "Famotidine",
    aliases: ["Pepcid"],
    category: "Digestive health",
    uses: "Reduces stomach acid to relieve and prevent heartburn.",
    typicalDosage: "Adults (OTC use): 10–20mg, up to twice daily.",
    sideEffects: "Headache, dizziness, constipation.",
    warnings: "See a doctor if heartburn persists more than 2 weeks or worsens.",
  },
  {
    name: "Loperamide",
    aliases: ["Imodium"],
    category: "Digestive health",
    uses: "Controls symptoms of diarrhea.",
    typicalDosage: "Adults: 4mg initially, then 2mg after each loose stool, max 8mg/day (OTC use).",
    sideEffects: "Constipation, dizziness, drowsiness.",
    warnings: "Do not use if you have bloody or black stool or a fever — see a doctor. Not for suspected bacterial infections without medical advice.",
  },
  {
    name: "Amoxicillin",
    aliases: [],
    category: "Antibiotics",
    uses: "Prescription antibiotic for bacterial infections (ear, throat, chest, urinary, and others).",
    typicalDosage: "As prescribed — commonly 250–500mg two to three times daily, depending on the infection.",
    sideEffects: "Nausea, diarrhea, rash.",
    warnings: "Prescription only. Finish the full course even if you feel better. Tell your pharmacist about any penicillin allergy.",
  },
  {
    name: "Azithromycin",
    aliases: ["Zithromax", "Z-Pak"],
    category: "Antibiotics",
    uses: "Prescription antibiotic for respiratory, skin, and certain other bacterial infections.",
    typicalDosage: "As prescribed — commonly a short course such as 500mg on day 1, then 250mg daily for 4 more days.",
    sideEffects: "Nausea, stomach pain, diarrhea.",
    warnings: "Prescription only. Can interact with several other medications — always share your full medication list with the prescriber.",
  },
  {
    name: "Sertraline",
    aliases: ["Zoloft"],
    category: "Mental health",
    uses: "Prescription SSRI for depression, anxiety, and related conditions.",
    typicalDosage: "As prescribed — commonly started at 25–50mg once daily, adjusted gradually.",
    sideEffects: "Nausea, sleep changes, sexual side effects, especially when starting.",
    warnings: "Prescription only. Do not stop suddenly — taper under medical guidance. Full effect can take several weeks.",
  },
  {
    name: "Alprazolam",
    aliases: ["Xanax"],
    category: "Mental health",
    uses: "Prescription benzodiazepine for short-term treatment of anxiety.",
    typicalDosage: "As prescribed — lowest effective dose for the shortest time needed.",
    sideEffects: "Drowsiness, dizziness, memory or coordination issues.",
    warnings: "Prescription only, controlled substance. Risk of dependence with prolonged use. Never combine with alcohol or opioids. Do not stop abruptly.",
  },
  {
    name: "Albuterol",
    aliases: ["Ventolin", "ProAir"],
    category: "Respiratory",
    uses: "Prescription fast-acting inhaler that relieves asthma and COPD symptoms like wheezing and shortness of breath.",
    typicalDosage: "As prescribed — commonly 1–2 puffs every 4–6 hours as needed for symptoms.",
    sideEffects: "Jitteriness, fast heartbeat, mild tremor.",
    warnings: "Prescription only. If you're using it more than twice a week for symptom relief, talk to your doctor about your asthma control plan.",
  },
  {
    name: "Fluticasone",
    aliases: ["Flonase"],
    category: "Allergy relief",
    uses: "Nasal spray that relieves nasal allergy symptoms — congestion, sneezing, runny/itchy nose.",
    typicalDosage: "Adults (OTC use): 1–2 sprays per nostril once daily.",
    sideEffects: "Nasal dryness or irritation, occasional nosebleed.",
    warnings: "Takes a few days of regular use for full effect. See a doctor if symptoms don't improve after a week of daily use.",
  },
  {
    name: "Levothyroxine",
    aliases: ["Synthroid"],
    category: "Thyroid health",
    uses: "Prescription hormone replacement for an underactive thyroid (hypothyroidism).",
    typicalDosage: "As prescribed — highly individualized, typically taken once daily on an empty stomach.",
    sideEffects: "Usually minimal at the correct dose; too high a dose can cause rapid heartbeat, anxiety, or weight loss.",
    warnings: "Prescription only. Take at the same time each day, on an empty stomach, and separate from calcium/iron supplements by several hours.",
  },
  {
    name: "Melatonin",
    aliases: [],
    category: "Sleep",
    uses: "Over-the-counter supplement used to help with occasional sleeplessness or jet lag.",
    typicalDosage: "Adults: commonly 1–5mg, taken 30–60 minutes before bedtime.",
    sideEffects: "Next-day grogginess, headache, mild nausea.",
    warnings: "Not tightly regulated as a supplement — dosages can vary by brand. Talk to a pharmacist before use if pregnant, breastfeeding, or on other medications.",
  },
  {
    name: "Hydrocortisone cream",
    aliases: ["Cortizone-10"],
    category: "Skincare",
    uses: "Relieves itching, redness, and irritation from insect bites, rashes, and mild eczema.",
    typicalDosage: "Apply a thin layer to the affected area up to 4 times daily (OTC strength), for no more than 7 days unless advised otherwise.",
    sideEffects: "Mild skin thinning or irritation with prolonged use.",
    warnings: "Avoid use on broken skin, the face, or in the eyes unless directed by a doctor. See a doctor if the condition doesn't improve.",
  },
  {
    name: "Warfarin",
    aliases: ["Coumadin"],
    category: "Heart health",
    uses: "Prescription blood thinner to prevent and treat blood clots.",
    typicalDosage: "As prescribed — highly individualized and requires regular blood testing (INR) to adjust the dose.",
    sideEffects: "Increased bruising or bleeding risk.",
    warnings: "Prescription only. Many food (especially vitamin K-rich greens) and drug interactions — consistency matters. Never adjust the dose yourself.",
  },
  {
    name: "Multivitamin",
    aliases: [],
    category: "Vitamins & supplements",
    uses: "General nutritional support to help fill gaps in a typical diet.",
    typicalDosage: "As directed on the product label, typically once daily with food.",
    sideEffects: "Mild stomach upset if taken without food.",
    warnings: "Not a substitute for a balanced diet. Keep iron-containing formulas away from children — iron overdose in kids is dangerous.",
  },
  {
    name: "Vitamin D3",
    aliases: ["Cholecalciferol"],
    category: "Vitamins & supplements",
    uses: "Supports bone health and immune function, especially with low sun exposure.",
    typicalDosage: "Commonly 600–2,000 IU daily for adults, though needs vary — a pharmacist or doctor can advise based on blood levels.",
    sideEffects: "Rare at recommended doses; very high doses over time can raise blood calcium.",
    warnings: "Don't exceed the label dose without medical guidance, especially if also taking calcium supplements.",
  },
];
